package KanapkaEngine.Net;

import KanapkaEngine.Components.Component;
import KanapkaEngine.Components.ImmutableCollection;
import KanapkaEngine.Editor.Attributes.ReadOnly;
import KanapkaEngine.Game.Logger;

import java.util.HashMap;
import java.util.HashSet;
import java.util.Random;
import java.util.Set;

public class NetworkIdentity extends Component {
    private static final Logger logger = new Logger("Networkidentity");

    protected static final HashMap<Integer, NetworkIdentity> loadedIdentities = new HashMap<>();

    @ReadOnly
    private final int NetID;

    @ReadOnly
    public boolean clientHasAuthority = false;

    private final Set<Integer> networkClientAuthority = new HashSet<>();

    /**
     * Net ids should only be generated by the server, and only assigned by the client so that there can be some sort of way to reference nodes.
     * @param NetID
     */
    public NetworkIdentity(int NetID) {
        this.NetID = NetID;

        loadedIdentities.put(NetID, this);
    }

    @Override
    public void onOrphan() {
        loadedIdentities.remove(this.getNetID());

        logger.log("Orhpaned");
    }

    @Override
    public void onDestroy() {
        loadedIdentities.remove(this.getNetID());

        logger.log("Destroyed");
    }

    public int getNetID() {
        return NetID;
    }

    public void Authorize(NetworkConnectionToClient client) {
        networkClientAuthority.add(client.getId());
    }

    public void DeAuthorize(NetworkConnectionToClient client) {
        networkClientAuthority.remove(client.getId());
    }

    public boolean hasAuthority(NetworkConnectionToClient client) {
        return networkClientAuthority.contains(client.getId());
    }

    public static NetworkIdentity find(int NetID) {
        return loadedIdentities.get(NetID);
    }

    public static int getRandomNetID() {
        Random random = new Random();
        int r;

        while (loadedIdentities.containsKey(r = Math.abs(random.nextInt()))) {

        }
        return r;
    }

    public static ImmutableCollection<NetworkIdentity> identities() {
        return new ImmutableCollection<>(loadedIdentities.values());
    }
}
